version: '3'

services:
  dd-agent:
    image: datadog/agent:latest
    container_name: dd-agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - ./datadog.yaml:/etc/datadog-agent/datadog.yaml
    environment:
      DD_API_KEY: "${DD_API_KEY}"
      DD_HOSTNAME: "js-metrics-poc"
      DD_ENV: "js-metrics-poc"
      DD_SITE: "datadoghq.com"
      DD_APM_ENABLED: true
      DD_LOGS_INJECTION: true
    ports:
      - "8126:8126"
    networks:
      - js-metrics-poc
  
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    depends_on:
      - webserver
    volumes:
      - ./frontend:/app/frontend
    ports:
      - 3000:3000
    networks:
      - js-metrics-poc
  
  webserver:
    build:
      context: ./webserver
    container_name: webserver
    ports:
      - "5000:5000"
    networks:
      - js-metrics-poc
  
  otel-collector:
    image: otel/opentelemetry-collector-contrib-dev:latest
    container_name: otel-collector
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "13133:13133"
      - "4317:4317"
      - "4318:4318"
    depends_on:
      - dd-agent
    networks:
      - js-metrics-poc
  
  jaeger-all-in-one:
    hostname: jaeger-aio
    image: jaegertracing/all-in-one:latest
    ports:
      - "16685"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
    depends_on:
      - otel-collector
    networks:
      - js-metrics-poc

networks:
  js-metrics-poc:
    driver: bridge

  